package com.biprom.bram.ui.views.inoxSubView;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Upload;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class InoxSubDesign extends Panel {
    protected Label infoLabel;
    protected Label infoLabelOpdracht;
    protected TextArea taKlant;
    protected TextArea taCommentaar;
    protected ListSelect<com.biprom.bram.backend.data.entity.mongodbEntities.Personeel> lsPersoneel;
    protected ComboBox<String> cbAantalPersonen;
    protected VerticalLayout vGridLayout;
    protected Grid<com.biprom.bram.backend.data.entity.mongodbEntities.Product> productGrid;
    protected Upload uploadFoto;
    protected CheckBox checkbVolledigUitgevoerd;
    protected GridLayout imageGird;

    public InoxSubDesign() {
        Design.read(this);
    }
}
