package com.biprom.bram.ui.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.CheckBoxGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Image;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.DateField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CheckListDesign extends VerticalLayout {
    protected Label titleLabel;
    protected Label vraagKlantLabel;
    protected CheckBoxGroup<com.biprom.bram.backend.data.entity.mongodbEntities.Personeel> checkbGroupTechniekers;
    protected CheckBoxGroup<String> cbgEUPallet;
    protected TextField tfBinnengebrachtAndereManier;
    protected ComboBox<String> cbPositieMagazijn;
    protected TextField tfAnderePositie;
    protected ComboBox<Integer> cbElektrischeAansluiting;
    protected Image imgElektrischeAansluiting;
    protected ComboBox<Integer> cbZijdeOntluchting;
    protected Image imgOntluchtingAansluiting;
    protected ComboBox<Integer> cbMontagePlaten;
    protected Image imgMontagePlatenAansluiting;
    protected TextArea taBijkomendCommentaarPomp;
    protected TextField tfUitGebreidPompType;
    protected TextField tfArtikelNummerPomp;
    protected TextField tfProductDatumPomp;
    protected TextField tfSerieNummerPomp;
    protected TextField tfLandPomp;
    protected TextField tfMotorType;
    protected TextField tfNominaalVermogen;
    protected TextField tfToerental;
    protected TextField tfArtikelNummerMotor;
    protected TextField tfUDriehoek;
    protected TextField tfUSter;
    protected CheckBox cbFreqController;
    protected CheckBox cbNietStandardPomp;
    protected TextField tfProductieDatumMotor;
    protected TextField tfIsolatieWeerstand;
    protected TextField tfRfase1;
    protected TextField tfRfase2;
    protected TextField tfRfase3;
    protected HorizontalLayout hLaytoutMotorElektrischInOrde;
    protected CheckBoxGroup<String> cbgMotorElektrischInOrde;
    protected VerticalLayout vLayoutMotorElektrisch;
    protected CheckBoxGroup<String> cbgIsolatieweerstand;
    protected CheckBoxGroup<String> cbgWikkelingswaardes;
    protected CheckBoxGroup<String> cbgMotorVerbrand;
    protected CheckBoxGroup<String> cbgControlBox;
    protected CheckBoxGroup<String> cbgWaterInMotor;
    protected TextField tfExtraCommentaarWaterInMotor;
    protected CheckBoxGroup<String> cbgMotorkabel;
    protected TextField tfCommentaarMotorkabel;
    protected CheckBoxGroup<String> cbgVochtInMotor;
    protected VerticalLayout vLayoutMotorMechanisch;
    protected CheckBoxGroup<String> cbgMotorLagers;
    protected TextField tfLagerAsMotorCommentaar;
    protected TextField tfLagerVentMotorCommentaar1;
    protected CheckBoxGroup<String> cbgMotorDichtingen;
    protected CheckBoxGroup<String> cbgVentilator;
    protected CheckBoxGroup<String> cbgBeschadingMotor;
    protected CheckBoxGroup<String> cbgGarantie;
    protected CheckBoxGroup<String> cbgBinnengebrachtPomp;
    protected TextField tfCommentaarPompBinnengebracht;
    protected CheckBoxGroup<String> cbgStaatPomp;
    protected TextField tfCommentaarPompDemonteerbaar;
    protected CheckBoxGroup<String> cbgPrimaireAsafdichtingen;
    protected TextField tfPrimaireAsafdichtingCommentaar;
    protected CheckBoxGroup<String> cbgSecundaireAsafdichtingen;
    protected TextField tfSecundaireAsafdichtingCommentaar;
    protected CheckBoxGroup<String> cbgPompas;
    protected TextField tfPompasCommentaar;
    protected CheckBoxGroup<String> cbgWaaiers;
    protected TextField tfWaaiersCommentaar;
    protected CheckBoxGroup<String> cbgKamers;
    protected TextField tfKamersCommentaar;
    protected CheckBoxGroup<String> cbgDichtingen;
    protected TextField tfDichtingenCommentaar;
    protected CheckBoxGroup<String> cbgAantasting;
    protected TextField tfAantastingCommentaar;
    protected CheckBoxGroup<String> cbgLagers;
    protected TextField tfLagersCommentaar;
    protected CheckBoxGroup<String> cbgSpaltringen;
    protected TextField tfSpaltRingenCommentaar;
    protected CheckBoxGroup<String> cbgBinnenwerk;
    protected CheckBoxGroup<String> cbgVuilInPomp;
    protected CheckBoxGroup<String> cbgStatusPomp;
    protected TextField tfPompStatusCommentaar;
    protected CheckBoxGroup<String> cbgPompBehandeling;
    protected DateTimeField dateDemontage;
    protected TextField tfUrenDemontage;
    protected CheckBox checkbBestekkostenAanrekenen;
    protected DateField datefHerstelDatum;
    protected DateTimeField dtUitersteHerstelDatum;
    protected TextField tfUrenHerstelling;
    protected TextField tfUrenReinigen;
    protected CheckBox checkbHerstellingAfgewerkt;
    protected TextField tfDebiet;
    protected TextField tfDruk;
    protected TextField tfDebietVuilWater;

    public CheckListDesign() {
        Design.read( this );
    }
}
